server:
  port: 19001

#LOG
logging:
  level:
    root: info
    jdbc.sqlonly: debug # SQL문만을 로그로 남기며, PreparedStatement일 경우 관련된 argument 값으로 대체된 SQL문이 보여진다.
    jdbc.audit: debug # ResultSet을 제외한 모든 JDBC 호출 정보를 로그로 남긴다.
    jdbc.resultset: debug # ResultSet을 포함한 모든 JDBC 호출 정보를 로그로 남긴다.
    jdbc.connection: debug #DB 연결, 연결 해제와 관련된 로그를 보여준다
    http.logging: debug
    org.springframework.test: warn
    com.amazonaws.util.EC2MetadataUtils: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] [%thread] [%logger{0}:%line] [%X{request_id:-startup}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level] [%thread] [%logger{0}:%line] [%X{request_id:-startup}] - %msg%n"

spring:
  profiles:
    active: local
  application:
    name: backend-api
