kakao:
  blog:
    url: https://dapi.kakao.com
  rest:
    key: dcbaac8be5d8afdbfcd8ba43c53ecc48

naver:
  blog:
    url: https://openapi.naver.com
  client:
    id: nROmKwKTe7215DnMfHs0
    secret: dYOAEcSSSo
